# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Team.delete_all
Serie.delete_all
Match.delete_all
Player.delete_all

# East Teams

cavaliers = Team.create!(name: "Cavaliers", conference: "east")
Player.create!(name: "LeBron James", team: cavaliers)
Player.create!(name: "Kyrie Irving", team: cavaliers)
Player.create!(name: "Channing Frye", team: cavaliers)
Player.create!(name: "Richard Jefferson", team: cavaliers)
Player.create!(name: "Kyle Korver", team: cavaliers)
Player.create!(name: "Kevin Love", team: cavaliers)
Player.create!(name: "Iman Shumpert", team: cavaliers)
Player.create!(name: "JR Smith", team: cavaliers)
Player.create!(name: "Tristan Thompson", team: cavaliers)
Player.create!(name: "Deron Williams", team: cavaliers)

wizards = Team.create!(name: "Wizards", conference: "east")
Player.create!(name: "John Wall", team: wizards)
Player.create!(name: "Bradley Beal", team: wizards)
Player.create!(name: "Bojan Bogdanovic", team: wizards)
Player.create!(name: "Marcin Gortat", team: wizards)
Player.create!(name: "Trey Burke", team: wizards)
Player.create!(name: "Brandon Jennings", team: wizards)
Player.create!(name: "Ian Mahinmi", team: wizards)
Player.create!(name: "Sheldon McClellan", team: wizards)
Player.create!(name: "Chris McCullough", team: wizards)
Player.create!(name: "Markieff Morris", team: wizards)
Player.create!(name: "Daniel Ochefu", team: wizards)
Player.create!(name: "Kelly Oubre Jr.", team: wizards)
Player.create!(name: "Otto Porter Jr.", team: wizards)
Player.create!(name: "Tomas Satoransky", team: wizards)
Player.create!(name: "Jason Smith", team: wizards)

hawks = Team.create!(name: "Hawks", conference: "east")
Player.create!(name: "Kent Bazemore", team: hawks)
Player.create!(name: "DeAndre Bembry", team: hawks)
Player.create!(name: "Jose Calderon", team: hawks)
Player.create!(name: "Malcolm Delaney", team: hawks)
Player.create!(name: "Mike Dunleavy", team: hawks)
Player.create!(name: "Tim Hardaway Jr.", team: hawks)
Player.create!(name: "Dwight Howard", team: hawks)
Player.create!(name: "Kris Humphries", team: hawks)
Player.create!(name: "Ersan Ilyasova", team: hawks)
Player.create!(name: "Ryan Kelly", team: hawks)
Player.create!(name: "Paul Millsap", team: hawks)
Player.create!(name: "Mike Muscala", team: hawks)
Player.create!(name: "Taurean Prince", team: hawks)
Player.create!(name: "Dennis Schroder", team: hawks)
Player.create!(name: "Thabo Sefolosha", team: hawks)

celtics = Team.create!(name: "Celtics", conference: "east")
Player.create!(name: "Avery Bradley", team: celtics)
Player.create!(name: "Jaylen Brown", team: celtics)
Player.create!(name: "Joe Crowder", team: celtics)
Player.create!(name: "Gerald Green", team: celtics)
Player.create!(name: "Al Horford", team: celtics)
Player.create!(name: "Demetrius Jackson", team: celtics)
Player.create!(name: "Jonas Jerebko", team: celtics)
Player.create!(name: "Amir Johnson", team: celtics)
Player.create!(name: "Jordan Mickey", team: celtics)
Player.create!(name: "Kelly Olynyk", team: celtics)
Player.create!(name: "Terry Rozier", team: celtics)
Player.create!(name: "Marcus Smart", team: celtics)
Player.create!(name: "Isaiah Thomas", team: celtics)
Player.create!(name: "James Young", team: celtics)
Player.create!(name: "Tyler Zeller", team: celtics)

bulls = Team.create!(name: "Bulls", conference: "east")
Player.create!(name: "Jimmy Butler", team: bulls)
Player.create!(name: "Isaiah Canaan", team: bulls)
Player.create!(name: "Michael Carter Williams", team: bulls)
Player.create!(name: "Cristiano Felicio", team: bulls)
Player.create!(name: "Jerian Grant", team: bulls)
Player.create!(name: "Joffrey Lauvergne", team: bulls)
Player.create!(name: "Robin Lopez", team: bulls)
Player.create!(name: "Nikola Mirotic", team: bulls)
Player.create!(name: "Anthony Morrow", team: bulls)
Player.create!(name: "Cameron Payne", team: bulls)
Player.create!(name: "Bobby Portis", team: bulls)
Player.create!(name: "Rajon Rondo", team: bulls)
Player.create!(name: "Denzel Valentine", team: bulls)
Player.create!(name: "Dwyane Wade", team: bulls)
Player.create!(name: "Paul Zipser", team: bulls)

bucks = Team.create!(name: "Bucks", conference: "east")
Player.create!(name: "Giannis Antetokounmpo", team: bucks)
Player.create!(name: "Michael Beasley", team: bucks)
Player.create!(name: "Malcolm Brogdon", team: bucks)
Player.create!(name: "Matthew Dellavedova", team: bucks)
Player.create!(name: "Spencer Hawes", team: bucks)
Player.create!(name: "John Henson", team: bucks)
Player.create!(name: "Thon Maker", team: bucks)
Player.create!(name: "Khris Middleton", team: bucks)
Player.create!(name: "Greg Monroe", team: bucks)
Player.create!(name: "Jabari Parker", team: bucks)
Player.create!(name: "Gary Payton II", team: bucks)
Player.create!(name: "Tony Snell", team: bucks)
Player.create!(name: "Mirza Teletovic", team: bucks)
Player.create!(name: "Jason Terry", team: bucks)
Player.create!(name: "Rashad Vaughn", team: bucks)

raptors = Team.create!(name: "Raptors", conference: "east")
Player.create!(name: "Bruno Caboclo", team: raptors)
Player.create!(name: "DeMarre Carroll", team: raptors)
Player.create!(name: "DeMar DeRozan", team: raptors)
Player.create!(name: "Serge Ibaka", team: raptors)
Player.create!(name: "Cory Joseph", team: raptors)
Player.create!(name: "Kyle Lowry", team: raptors)
Player.create!(name: "Lucas Nogueira", team: raptors)
Player.create!(name: "Patrick Patterson", team: raptors)
Player.create!(name: "Jakob Poeltl", team: raptors)
Player.create!(name: "Norman Powell", team: raptors)
Player.create!(name: "Pascal Siakam", team: raptors)
Player.create!(name: "PJ Tucker", team: raptors)
Player.create!(name: "Jonas Valanciunas", team: raptors)
Player.create!(name: "Fred VanVleet", team: raptors)
Player.create!(name: "Delon Wright", team: raptors)

# West Teams

warriors = Team.create!(name: "Warriors", conference: "west")
Player.create!(name: "Matt Barnes", team: warriors)
Player.create!(name: "Stephen Curry", team: warriors)
Player.create!(name: "Kevin Durant", team: warriors)
Player.create!(name: "Draymond Green", team: warriors)
Player.create!(name: "Andre Iguadala", team: warriors)
Player.create!(name: "Shaun Livingston", team: warriors)
Player.create!(name: "JaVale McGee", team: warriors)
Player.create!(name: "Klay Thompson", team: warriors)

spurs = Team.create!(name: "Spurs", conference: "west")
Player.create!(name: "Patrick Mills", team: spurs)
Player.create!(name: "Tony Parker", team: spurs)
Player.create!(name: "Dejounte Murray", team: spurs)
Player.create!(name: "Manu Ginóbili", team: spurs)
Player.create!(name: "Danny Green", team: spurs)
Player.create!(name: "Jonathon Simmons", team: spurs)
Player.create!(name: "Kawhi Leonard", team: spurs)
Player.create!(name: "Kyle Anderson", team: spurs)
Player.create!(name: "David Lee", team: spurs)
Player.create!(name: "LaMarcus Aldridge", team: spurs)
Player.create!(name: "Pau Gasol", team: spurs)
Player.create!(name: "Joel Anthony", team: spurs)
Player.create!(name: "Dewayne Dedmon", team: spurs)

rockets = Team.create!(name: "Rockets", conference: "west")
Player.create!(name: "Patrick Beverley", team: rockets)
Player.create!(name: "Isaiah Taylor", team: rockets)
Player.create!(name: "Bobby Brown", team: rockets)
Player.create!(name: "James Harden", team: rockets)
Player.create!(name: "Louis Williams", team: rockets)
Player.create!(name: "Eric Gordon", team: rockets)
Player.create!(name: "Troy Williams", team: rockets)
Player.create!(name: "Trevor Ariza", team: rockets)
Player.create!(name: "Sam Dekker", team: rockets)
Player.create!(name: "Montrezl Harrell", team: rockets)
Player.create!(name: "Ryan Anderson", team: rockets)
Player.create!(name: "Kyle Wiltjer", team: rockets)
Player.create!(name: "Clint Capela", team: rockets)
Player.create!(name: "Chinanu Onuaku", team: rockets)
Player.create!(name: "Nene Hilario", team: rockets)

clippers = Team.create!(name: "Clippers", conference: "west")
Player.create!(name: "Chris Paul", team: clippers)
Player.create!(name: "Raymond Felton", team: clippers)
Player.create!(name: "Austin Rivers", team: clippers)
Player.create!(name: "Jamal Crawford", team: clippers)
Player.create!(name: "J.J. Redick", team: clippers)
Player.create!(name: "Alan Anderson", team: clippers)
Player.create!(name: "Wesley Johnson", team: clippers)
Player.create!(name: "Paul Pierce", team: clippers)
Player.create!(name: "Luc Mbah a Moute", team: clippers)
Player.create!(name: "Brandon Bass", team: clippers)
Player.create!(name: "Brice Johnson", team: clippers)
Player.create!(name: "Blake Griffin", team: clippers)
Player.create!(name: "Marreese Speights", team: clippers)
Player.create!(name: "DeAndre Jordan", team: clippers)
Player.create!(name: "Diamond Stone", team: clippers)

jazz = Team.create!(name: "Jazz", conference: "west")
Player.create!(name: "Raul Neto", team: jazz)
Player.create!(name: "George Hill", team: jazz)
Player.create!(name: "Shelvin Mack", team: jazz)
Player.create!(name: "Dante Exum", team: jazz)
Player.create!(name: "Alec Burks", team: jazz)
Player.create!(name: "Gordon Hayward", team: jazz)
Player.create!(name: "Rodney Hood", team: jazz)
Player.create!(name: "Joe Johnson", team: jazz)
Player.create!(name: "Joe Ingles", team: jazz)
Player.create!(name: "Trey Lyles", team: jazz)
Player.create!(name: "Boris Diaw", team: jazz)
Player.create!(name: "Joel Bolomboy", team: jazz)
Player.create!(name: "Derrick Favors", team: jazz)
Player.create!(name: "Jeff Withey", team: jazz)
Player.create!(name: "Rudy Gobert", team: jazz)

# East Series

Serie.create!(team_a: cavaliers, team_b: raptors)
Serie.create!(team_a: bulls, team_b: wizards)

# West Series

Serie.create!(team_a: warriors, team_b: clippers)
Serie.create!(team_a: rockets, team_b: spurs)
